version: "2.1"

networks:
  aether:
    external:
      name: aether_internal

services:

  # ---------------------------------
  # Database container
  # ---------------------------------

  db:
    extends:
      file: aether-bootstrap/docker-compose-base.yml
      service: postgres-base
    networks:
      - aether

  # ---------------------------------
  # Aether kernel container
  # ---------------------------------

  kernel:
    extends:
      file: aether-bootstrap/docker-compose-base.yml
      service: kernel-base
    depends_on:
      - db
    networks:
      aether:
        aliases:
          - kernel.aether.local

  # ---------------------------------
  # ODK Adapter container
  # ---------------------------------

  odk:
    extends:
      file: aether-bootstrap/docker-compose-base.yml
      service: odk-base
    depends_on:
      - db
      - kernel
    networks:
      aether:
        aliases:
          - odk.aether.local

  # ---------------------------------
  # Aether UI container
  # ---------------------------------

  ui:
    extends:
      file: aether-bootstrap/docker-compose-base.yml
      service: ui-base
    depends_on:
      - db
      - kernel
    networks:
      aether:
        aliases:
          - ui.aether.local

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: docker-compose-base.yml
      service: gather-base
    depends_on:
      - db
      # - gather-webpack
      - kernel
      - odk
    networks:
      aether:
        aliases:
          - gather.local

  # ---------------------------------
  # Gather Webpack container
  # ---------------------------------

  # gather-webpack:
  #   extends:
  #     file: docker-compose-base.yml
  #     service: gather-webpack-base
  #   networks:
  #     - aether

  # ---------------------------------
  # NGINX container
  # ---------------------------------

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx-base
    depends_on:
      - gather
      - kernel
      - odk
      - ui
    networks:
      - aether
